name: BedrockConnect
description: Create a issue to help me fix the instance
body:
  - type: markdown
      value: |
      Hi and thanks for filling this issue out, please make sure to fill everything out so we can fix the problem as fast as possilbe, if you arent sure about something then just add a "-" in the field.
  - type: input
    attributes:
      label: Minecraft Bedrock Version
      description: Which Bedrock Version are YOU currently using to join the instance?
      placeholder: |
        Example: 1.20.70
      validations:
        required: false
  - type: input
    attributes:
      label: DNS or MCXboxBroadcast?
      description: Are you using the DNS Server to connect or the Xbox account MCBEFC?
      placeholder: |
        Either "DNS" Or "MCBEFC"
      validations:
        required: false
  - type: input
    attributes:
      label: (MCBEFC Only) Server Version
      description: What version does the Minecraft account display to you?
      placeholder: |
        Example: 1.20.70
      validations:
        required: false
  