blank_issues_enabled: true
contact_links:
  - name: BedrockConnect Repository
    url: https://github.com/Pugmatt/BedrockConnect
    about: Problems with the Server Browser itself? Report the issue here!!
